name: Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install --no-package-lock
      - run: npm test -- --run
